#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(master|develop)$|(feature|release|hotfix)\/[a-z0-9._-]+$|^HEAD$"

message="你的分支名称有问题。本项目中的分支名称必须遵守本规则:$valid_branch_regex。您的提交将被拒绝。您应该将分支重命名为有效名称，然后重试。"

if [[ ! $local_branch =~ $valid_branch_regex ]]; then
  echo "$message"
  echo "${local_branch}"
  exit 1
fi

exit 0
